Insamling av punktmoln
PUM-9/point_cloud_handler pull request #1
Opened 2017-03-01 11:44 UTC by FredrikWallstrom

Ihopsamlingen av punktmoln har fungerat bra. Det var lite krångel i början med att det inte gick att genomföra X antal scanningar på rad. Jag har dock kört några gånger nu och det verkar fungera stabilt, inga fler missöden med det iaf. Kanske berodde på att Windows datorn går i viloläge? Det har ej testats i alla fall.

Ihopsamlingen testas genom att först köra igång wrappern, det gör du med kommandot:
rosrun treedwrapper main.py

I en ny terminal kör du sedan igång point_cloud_handler servicen, det gör du genom att först kompilera med catkin_make, sedan kör du kommandot:
rosin point_cloud_handler main

Du bör nu kunna anropa point_cloud_handler servicen med kommandot:
rosservice call /get_point_cloud X
Där X är vilken accuracy du vill köra med (accuracy 1 och 2 går fort, 3 går också relativt bra mesans 4 så tar det ganska lång tid att köra igenom).

Just nu returneras det första punktmolnet vid genomförd scanning, vilket sen ska ändras när registreringen är implementerad.

## Felhantering
1. Om det av någon anledning gick snett med anropet till wrapper servicen.
2. Koll så att accuracy är större än 0

2017-03-01 12:52 UTC, ehmanx commented on src/main.cpp
> +    This function will get the gather point clouds that will be stored in a vector.
this function will get the gather point clouds? jag fattar inte meningen

2017-03-01 12:56 UTC, ehmanx reviewed
Allt ser bra ut men jag tycker att vi ska skriva om kommentaren som jag lämnade en comment på

2017-03-01 13:07 UTC, olofholmberg commented on src/main.cpp
> +    This function will get the gather point clouds that will be stored in a vector.
Kan ju bytas till "This function will scan an object and register all the pointclouds to a resulting pointcloud."

2017-03-01 17:37 UTC, Dunstrom requested changes
Över lag schysst kod! Jättebra med felhantering om accuracy är mindre än 0 fortsätt med det och lägg till felhantering om accuracy är för hög. Sen var det en oklar kommentar, fixa det så är det perfa sen!

2017-03-01 17:37 UTC, Dunstrom commented on src/main.cpp
> +    if (req.accuracy <= 0) {
Vi har väl sag att accuracy ska vara mellan 0-10 så vi kan väl kolla hela den grejen så man inte skickar in 100 och får vänta i år och dar.

2017-03-01 17:37 UTC, Dunstrom commented on src/main.cpp
> +
onödig tom rad imo, men ingen big deal. Jag tycker att om man ska köra tom rad i början borde man göra det i slutet också annars blir det okonsekvent men man gör som man vill :)

2017-03-01 17:37 UTC, Dunstrom commented on src/main.cpp
> +    This function will get the gather point clouds that will be stored in a vector.
Håller med, den här kommentaren borde skrivas om.

2017-03-01 20:38 UTC, FredrikWallstrom commented
Hur approvar man changes? Eller ska inte jag göra någonting nu när jag har commitat?

2017-03-02 14:01 UTC, Dunstrom approved these changes
Nu är jag nöjd och alla andra verkar vara det med.

2017-03-02 14:01 UTC, merged